### Variáveis
@baseUrl = http://localhost:8000/api
@token = bdfaf18330537792565850ad185efc6d13141a4b

### Registrar um novo usuário
POST {{baseUrl}}/accounts/signup/
Content-Type: application/json

{
  "email": "usuario2@exemplo.com",
  "password": "senha_segura123",
  "password_confirm": "senha_segura123",
  "first_name": "Nome",
  "last_name": "Sobrenome",
  "phone": "99999999999",
  "role": "motorista"
}

### Login
POST {{baseUrl}}/accounts/login/
Content-Type: application/json

{
  "email": "usuario1@exemplo.com",
  "password": "senha_segura123"
}

### Testar token (copie o token da resposta do login acima)
GET {{baseUrl}}/accounts/test-token/
Authorization: Token {{token}}

### Logout
POST {{baseUrl}}/accounts/logout/
Authorization: Token {{token}}