### Variáveis
@baseUrl = http://localhost:8000/api
@token = f2224f9bdf7b96a19643bfdb30c9cc91dbe0917b

### Registrar um novo usuário
POST {{baseUrl}}/accounts/signup/
Content-Type: application/json

{
  "email": "cristian.rst222@hotmail.com",
  "password": "123456",
  "password_confirm": "123456",
  "first_name": "Arthur",
  "last_name": "Sobrenome",
  "phone": "11999532631",
  "role": "motorista",
  "cpf": "45495658881 "
}

### Login
POST {{baseUrl}}/accounts/login/
Content-Type: application/json

{
  "email": "cristian.rst@hotmail.com",
  "password": "123456"
}

### Testar token (copie o token da resposta do login acima)
GET {{baseUrl}}/accounts/test-token/
Authorization: Token {{token}}

### Logout
POST {{baseUrl}}/accounts/logout/
Authorization: Token {{token}}

### Listar usuários
GET {{baseUrl}}/accounts/list-users/
