### Variáveis
@baseUrl = http://localhost:8000/api
@token = 2e35ba5199655be25ec3c26c6a647cd0850e61a5

### Criar um novo checkin (como motorista)
POST {{baseUrl}}/checkins/criar/
Authorization: Token {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="comentario"

Chegada no cliente para entrega
------WebKitFormBoundary
Content-Disposition: form-data; name="arquivos"; filename="logo_escrita_direita.png"
Content-Type: image/png

< ./logo_escrita_direita.png
------WebKitFormBoundary
Content-Disposition: form-data; name="arquivos"; filename="logoSimples.jpeg"
Content-Type: image/jpeg

< ./logoSimples.jpeg
------WebKitFormBoundary--

### Listar todos os checkins
GET {{baseUrl}}/checkins/
Authorization: Token {{token}}

### Listar apenas checkins pendentes (para logística)
GET {{baseUrl}}/checkins/pendentes/
Authorization: Token {{token}}

### Ver detalhes de um checkin específico
GET {{baseUrl}}/checkins/4/
Authorization: Token {{token}}

### Aprovar um checkin (como logística)
POST {{baseUrl}}/checkins/1/aprovar/
Authorization: Token {{token}}
Content-Type: application/json

{
  "comentario_avaliacao": "Aprovado. Checkin realizado corretamente."
}

### Rejeitar um checkin (como logística)
POST {{baseUrl}}/checkins/2/rejeitar/
Authorization: Token {{token}}
Content-Type: application/json

{
  "comentario_avaliacao": "Rejeitado. Faltam informações importantes."
}

### Adicionar mais arquivos a um checkin existente
POST {{baseUrl}}/checkins/3/upload-arquivo/
Authorization: Token {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="arquivos"; filename="foto_adicional.jpg"
Content-Type: image/jpeg

< ./foto_adicional.jpg
------WebKitFormBoundary--